### ISSUE TITLE
[BUG] Audio quality

### ISSUE THREAD

**Issue by kaos126** [ananjaser1211/FloydQ_8890#15]
audio compared to an old Rom is higher but is heard with less bass. It is very noticeable with the charging sound at maximum system volume

**Comment by Fild5x** [comment]
On my phone it is the perfect sound I was ever looking for. With the use of 3rd party apps and sound mods. Perfect.

**Comment by youmoLC** [comment]
The sound quality is very perfect as BlackDiamond 5.1! Why it was described as BUG?

**Comment by Fild5x** [comment]
The quality is pretty poor without a sound mod like viper4a. But with that, it becomes even better than any other  rom I ever used in my life of custom roms

**Comment by kukuhajip** [comment]
When video call using whatsapp, volume increase if i touch proximity sensor. Then i try another app (e.g telephone, music no problem). Anyone notice this bug?

**Comment by ananjaser1211** [comment]
Few patches later, we found bunch of culpurts for this
1) There was an issue with audio processing, once fixed the rom sounded better
2) Q .ogg files are 7db louder tahn Pie, we will fix this by changing the media files to S10 which are the same except not 7db louder.

**Comment by ananjaser1211** [comment]
Discussion for this BUG has been moved to #59
