### ISSUE TITLE
[BUG] AR EMOJI not working, it isnt installed

### ISSUE THREAD

**Issue by chad078** [ananjaser1211/FloydQ_8890#20]
**Describe the bug**
Describe your issue here. 

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930F]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by chad078** [comment]
[Request] AR Emoji feature

**Comment by ananjaser1211** [comment]
AR Emoji toggle will be removed, it relies on CoreV2 camera setup and that is not something you can port. i mistook this for the simpler my emoji found on Older devices.
