### ISSUE TITLE
[BUG] PUBG lags too much..its not playeble

### ISSUE THREAD

**Issue by chad078** [ananjaser1211/FloydQ_8890#21]
**PUBG IS NOT PLAYEBLE**
Hello, I started pubg but it lags too much maybe bcoz of game optimisation service apk installed in system..I was using Black Diamond V8 with Same kernel but pubg was running well..now its not like that...I tried to remove game optimisation service app but I couldn't...Please help me

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930F]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by ananjaser1211** [comment]
You are not supposed to remove game optimization, the F.A.Q mentions that 

Q : Games are Laggy/Pix-elated/Stutter/sucks/crashes
A : Open GameLauncher > Top Left menu > Game Performance > Set Game performance to "Focus on PowerSaving"
- The other options might work for some games, but they also break others.
- This ensures the game run at native resulotion and without any hiccups

This will set the performance level similar to Pie
