### ISSUE TITLE
[BUG] No Audio below certain point

### ISSUE THREAD

**Issue by shariq342** [ananjaser1211/FloydQ_8890#26]
**Describe the bug**
If you Play any music or video & set the volume at 5 or 6 , You won't hear a sound. in simple words below volume 7 there is no sound through speaker and jack. didn't tried BT
**To Reproduce**
1. Go to S Music or Youtube or Video Player
2. Play any Music or video
3. Set the Volume slider below 7 Points
4. no Sound...

**Expected behavior**
Basically No Sound

**Smartphone (please complete the following information):**
 - Device: [Galaxy S7]
 - Model: [G930w8]

[logall.txt](https://github.com/ananjaser1211/FloydQ_8890/files/4515660/logall.txt)

**Comment by ananjaser1211** [comment]
Discussion for this BUG has been moved to #59
