### ISSUE TITLE
[IMPROVEMENT] Quick Settings UI to fill up the screen

### ISSUE THREAD

**Issue by kotn3l** [ananjaser1211/FloydQ_8890#27]
When expanding Quick Settings, it doesn't fill up the screen all the way, there is a gap. (Is it intentional? On Pie NFE it filled up all the way. Not on Pie N8 though, probably due to screen aspect ratio difference?) Very minor issue.
![Screenshot_20200420-152809_Google Play Store](https://user-images.githubusercontent.com/32578937/79978394-20507900-84a0-11ea-8f46-bcb0111fa816.jpg)

**Comment by ananjaser1211** [comment]
This is indeed due to the non 16:9 nature of the port, but fixing such issue requires deodexing the framework.jar (which causes significant issues) or bypassing "infintiy display" detection somehow.
which is alot for something insignificant
