### ISSUE TITLE
[BUG] Volume settings not working correctly

### ISSUE THREAD

**Issue by Skyterix1991** [ananjaser1211/FloydQ_8890#28]
**Describe the bug**
The audio behaves in some situations like it doesn't respond to volume change. Mainly notification sounds.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set volume to almost minimum
2. Connect charger
3. Sound will ignore current volume settings and be very loud.

P.S Sometimes I noticed this behaviour when using Messenger.

**Smartphone:**
 - Device: Galaxy S7
 - Model: G930F

**Comment by sandeepsp121** [comment]
It doesn't matter whether you plugin the charger or not it behaviour is very odd even without plugin the charger.

**Comment by ananjaser1211** [comment]
Discussion for this BUG has been moved to #59
