### ISSUE TITLE
[Bug] battery bug maybe?

### ISSUE THREAD

**Issue by albertodurmiendo** [ananjaser1211/FloydQ_8890#32]
I don't know if this is a bug, incorrect battery percentage.

This occurs after I accidentally leave my phone charge overnight while turned off.

After booting up it shows 100% for 3 hrs (with slight usage)

I boot to twrp and shows 86% of battery but when I boot to rom still 100%

If needed to send log file via logcat, someone teach me how 🤣

Update: After clearing cache, after some minutes my battery now shows 98%

**Comment by ananjaser1211** [comment]
Rely on the % reported by your system, and not TWRP. 
it uses different charger / different measurements

granted, 14% different is rather large, if it keeps happening, consider recalibration
