### ISSUE TITLE
[BUG] Phone goes silent,even if it is on sound.

### ISSUE THREAD

**Issue by B3rthelot** [ananjaser1211/FloydQ_8890#33]
**Describe the bug**
Yesterday i was listening to music,then i left the phone because i had some work to do.After 4 hours,i had returned to my phone wanting to listen to music again.Saw that the music was on,but I was unable to listen to it because it was mute.Then i started changing the volume low-high for media,ringtone,system,still the same problem.Same when i was changing to Sound-Vibrate-Mute ... no sound when choosing Sound.The phone was completely mute.Had to restart it.

I had the Blue light Filter schedule on,so I THINK that the problem might get started from there,I am not so sure.

 - Device: S7 Edge
 - Model: SM-G935F

**Comment by ananjaser1211** [comment]
Discussion for this BUG has been moved to #59
