### ISSUE TITLE
[BUG] Apps boot slowly,some of them freeze.

### ISSUE THREAD

**Issue by B3rthelot** [ananjaser1211/FloydQ_8890#34]
Apps like Facebook,instagram,discord,snapchat boot slow,i think i have to wait more than 4-5 seconds to boot properly.
In snapchat for example,it sometimes freeze when i try to change the camera,and after that the camera seems crappy,is moving sluggish and you can't properly see the objective.

-Those apps are updated.

 - Device: S7 Edge
 - Model: SM-G935F

**Comment by johnybr99** [comment]
Did you maybe clear cache and dalvik-cache after you flashed the rom?

**Comment by shariq342** [comment]
There is no such issue on Floyd with default kernel. 
This issue can only come if you have done terrible tweaks of yourself. @ananjaser1211 Close this issue.

Regards,
@MissACCA
