### ISSUE TITLE
[BUG] Notification LED doesn't light up properly 

### ISSUE THREAD

**Issue by amit-kj** [ananjaser1211/FloydQ_8890#38]
**Describe the bug**
LED does not light (green light) when getting notifications from  apps such as Facebook,  wechat, phone missed calls etc except only phone charging LED Light.

.
.

**Smartphone (please complete the following information):**
 - Device: Galaxy S7 edge
 - Model:  G935FD

**Additional context**
- here's logs..
[alogcat.2020-04-23-14-11-29+0600.txt](https://github.com/ananjaser1211/FloydQ_8890/files/4521155/alogcat.2020-04-23-14-11-29%2B0600.txt)

**Comment by jame25** [comment]
Notifications (audio and LED light) usually work for me, however a Whatsapp msg only gives a short audio notification and no light.

Log:
[alogcat.2020-04-25-10-47-45+0100.txt](https://github.com/ananjaser1211/FloydQ_8890/files/4532734/alogcat.2020-04-25-10-47-45%2B0100.txt)

**Comment by ananjaser1211** [comment]
Any more reports on this issue ? i recive Blue LED for facebook notifications and Green LED with whatsapp (granted i only had whatsapp installed for 2 hours)

**Comment by shariq342** [comment]
LED are working Fine. Tested by sending calls and sms from my Main phone to my S7. Check your notification settings. Or check your led by dialing *#0*# (Check ScreenShot for more detail view)


![Screenshot_20200504-040105_HwModuleTest](https://user-images.githubusercontent.com/61206202/80928128-083ffa00-8dbc-11ea-9811-594bdf8b4106.jpg)

Regards,
@MissACCA

**Comment by ananjaser1211** [comment]
Can confirm. leds are indeed working fine. and since no one else seems to report this issue, ill close it

**Comment by amit-kj** [comment]
now the LED is working fine. Thanks for ur support :D
