### ISSUE TITLE
[BUG]Theme Park don't work

### ISSUE THREAD

**Issue by Ruvera** [ananjaser1211/FloydQ_8890#39]
Theme park is constantly standing. I am creating my own theme and it gives an error when I press the save button.

**Comment by Illmind** [comment]
Update it and it'll work.

**Comment by ananjaser1211** [comment]
All Goodlock apps can be found here : http://downloads.corsicanu.ro/GoodLock

Reinstall themepark from there and it should work. i cant test it right now on the phone itself but thats probably the issue.
