### ISSUE TITLE
Bateria se agota muy rapido

### ISSUE THREAD

**Issue by ariegasel** [ananjaser1211/FloydQ_8890#43]
Buenos días!!! Llevo probando la rom 3 días, me encanta, es muy Bonita, pero tengo un problema, es que la bateria se me agota muy rápido, ayer tenía el móvil al 100% de batería a las 9 a.m y para las 18hs me quedaban 4% y en esa franja horaria estuve trabajando, lo use muy poco, anoche cuando me fui a dormir tenia un 50% y en 6 horas sin usarlo, se consumió toda! Alguna solución???

**Comment by SkyrilHD** [comment]
Good Morning!!!  I have been testing the rom for 3 days, I love it, it is very beautiful, but I have a problem, it is that the battery runs out very quickly, yesterday I had the phone at 100% battery at 9 am and by 18:00 I had 4% left  And in that time slot I was working, I used it very little, last night when I went to sleep it was 50% and in 6 hours without using it, it was all consumed!  Any solution???

**Comment by ananjaser1211** [comment]
Lack of info, use better battery status to figure out why.
