### ISSUE TITLE
[BUG] video stabilization not working at any resolution 

### ISSUE THREAD

**Issue by kukuhajip** [ananjaser1211/FloydQ_8890#45]
**Describe the bug**
Video stabilization not working at all even change video resolution 

**To Reproduce**
1. Go to camera (front camera)
2. Open setting
3. Video setting
![Screenshot_20200424-200835_Camera](https://user-images.githubusercontent.com/64263899/80216616-87208e80-8668-11ea-889d-ae32559606f2.jpg)

**Smartphone (please complete the following information):**
 - Device: [Galaxy S7 edge]
 - Model: [G935FD]

**Comment by ananjaser1211** [comment]
Duplicate #8

**Comment by gusttavh** [comment]
Not stabilization
