### ISSUE TITLE
[BUG] Unable to answer Viber voice call

### ISSUE THREAD

**Issue by jame25** [ananjaser1211/FloydQ_8890#48]
**Describe the bug:**
Incoming Viber call. Phone rings, but no 'answer / reject' screen appears or is accessible (I tried).

**Comment by jame25** [comment]
I just had a Viber call work without this issue. Unsure if the audio fix resolved it.

**Comment by ananjaser1211** [comment]
> I just had a Viber call work without this issue. Unsure if the audio fix resolved it.

The audio fix should help with this, but ill wait for more confirmations before closing off this issue, if possible do more viber calls. VOIP is blocked in my country so i cant do much

**Comment by jame25** [comment]
In subsequent tests, Viber has worked without issue and as expected.

**Comment by ananjaser1211** [comment]
Alright , thanks for the info. ill close this issue
