### ISSUE TITLE
Mobile data dosen't work

### ISSUE THREAD

**Issue by ReXXor12** [ananjaser1211/FloydQ_8890#52]
**Describe the bug**
Hello, i just installed the rom and i noticed the mobile data dosen't work, it's says insert sim card to acces network services and also the samsung account fails on login. I have a fully functional sim card insterted but he dosen't want to work.

**To Reproduce**
1. Go to 'control center'
2. Click on 'mobile data'
3. Scroll down to ''
4. See error '' insert sim card to acces network services''

**Expected behavior**
i expected to have minor bugs not bugs on the network.

**Screenshots**
https://imgur.com/Bi4HuVv

**Smartphone (please complete the following information):**
 - Device: [Galaxy S7 Edge]
 - Model: [e.g. G965F]

**Additional context**
I don't know how to find these logs.

**Comment by jame25** [comment]
Zero issues with mobile data here. It's important to follow the flashing instructions correctly.

**Comment by ReXXor12** [comment]
i don't know, maybe this rom it's for dual version. I installed last version of twrp same for magisk, the boot loader has been changed for the root and i followed the instruction. Before this rom i had android 9.0 pie blackdiamond and no issues with after 5 months.

**Comment by ananjaser1211** [comment]
When installing the ROM, select a CSC such as BTU in the list

**Comment by ReXXor12** [comment]
> 
> 
> When installing the ROM, select a CSC such as BTU in the list

i will reinstall and give u more info.

**Comment by ReXXor12** [comment]
> 
> 
> > When installing the ROM, select a CSC such as BTU in the list
> 
> i will reinstall and give u more info.

Same issue

**Comment by ReXXor12** [comment]
This rom supports the French country or sim cards?

**Comment by ananjaser1211** [comment]
it supports ALl countries and simcards, so im not sure why its failing on your end.
the only suggestion is a bad CSC (some brazilian regions had that issue and fixed it by picking BTU)
besides that i got no clue

**Comment by ReXXor12** [comment]
> 
> 
> it supports ALl countries and simcards, so im not sure why its failing on your end.
> the only suggestion is a bad CSC (some brazilian regions had that issue and fixed it by picking BTU)
> besides that i got no clue

It's wierd but i will try all the CSC and if that dosen't work i will wait a newer version. Btw nice work.

**Comment by jame25** [comment]
When I flashed the ROM on Single-SIM SM-G935F, I choose 'use previous CSC.' I never encountered any problems.

**Comment by ReXXor12** [comment]
> 
> 
> When I flashed the ROM on Single-SIM SM-G935F, I chose 'use previous CSC.' I never encountered any problems.

''use previous CSC'' does mean the rom takes the csc of the last rom used?

**Comment by ananjaser1211** [comment]
previous CSC will read mps_code.dat in your EFS, and load the CSC based on that, it works for most people however the rom does not contain every single CSC code. (because samsung limits each region to 50/60 codes)

So for those users who cant detect a matching mps_code.dat to a avalible csc, it will set the default which is XSG, this is causing some users to get msg like "re insert sim" or "reboot to finish sim setup"

**Comment by ReXXor12** [comment]
> 
> 
> previous CSC will read mps_code.dat in your EFS, and load the CSC based on that, it works for most people however the rom does not contain every single CSC code. (because samsung limits each region to 50/60 codes)
> 
> So for those users who cant detect a matching mps_code.dat to a avalible csc, it will set the default which is XSG, this is causing some users to get msg like "re insert sim" or "reboot to finish sim setup"

I understand, at least i made an video for showing u how i install the rom and what it shows me when i'm on configuration setup.

**Comment by ReXXor12** [comment]
I found out what happen, the phone do not recognize any more the sim card. It was not the rom. Thanks for helping.

**Comment by ananjaser1211** [comment]
> I found out what happen, the phone do not recognize any more the sim card. It was not the rom. Thanks for helping.

Could you let me know what was the issue when you find out ? Thankyou

**Comment by ReXXor12** [comment]
The phone don't recognize any sim card, i tried to change the sim cards and it's not working. After that i backup the phone at the original rom and the same issue. I think the phone broke but not at all, just the reader of the sim card because the rom dosen't show the imei number. Sorry for disturbing you.
