### ISSUE TITLE
[BUG] Edge panels scaling issues

### ISSUE THREAD

**Issue by Switchof** [ananjaser1211/FloydQ_8890#53]
**Describe the bug**
smart select

**To Reproduce**
1. Go to 'edge panel'
2. Click on 'smart select'

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: Galaxy S7E
 - Model: G935F

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable
![20200426_231632](https://user-images.githubusercontent.com/64365899/80311908-e91df700-8814-11ea-966c-2665b3a9a53d.jpg)

**Comment by Switchof** [comment]
Encounter another issue when edit above screenshot using photo editor app.After update photo editor app it giving fc and need to uninstall update for using it

**Comment by ananjaser1211** [comment]
> Encounter another issue when edit above screenshot using photo editor app.After update photo editor app it giving fc and need to uninstall update for using it
Did you change DPI ? and did you flash anything else, manual debloat etc

Cuz i have neither of these issues on my end. can someone else confirm ?
![photo_2020-04-26_19-56-15](https://user-images.githubusercontent.com/25624482/80312754-1314f080-87f8-11ea-8def-af7b4bff57ab.jpg)

![photo_2020-04-26_19-56-11](https://user-images.githubusercontent.com/25624482/80312753-11e3c380-87f8-11ea-9421-b0d359c03880.jpg)

**Comment by johnybr99** [comment]
> > Encounter another issue when edit above screenshot using photo editor app.After update photo editor app it giving fc and need to uninstall update for using it
> 
> Did you change DPI ? and did you flash anything else, manual debloat etc
> Cuz i have neither of these issues on my end. can someone else confirm ?
> ![photo_2020-04-26_19-56-15](https://user-images.githubusercontent.com/25624482/80312754-1314f080-87f8-11ea-8def-af7b4bff57ab.jpg)
> 
> ![photo_2020-04-26_19-56-11](https://user-images.githubusercontent.com/25624482/80312753-11e3c380-87f8-11ea-9421-b0d359c03880.jpg)

I can confirm that Smart Select and Apps Edge have some scaling issues.
![Screenshot_20200426-234226_Chrome](https://user-images.githubusercontent.com/14318631/80320608-a9a4da00-8817-11ea-9cc0-bf0c3ff621b1.png)

**Comment by Switchof** [comment]
> > Encounter another issue when edit above screenshot using photo editor app.After update photo editor app it giving fc and need to uninstall update for using it
> 
> Did you change DPI ? and did you flash anything else, manual debloat etc
> Cuz i have neither of these issues on my end. can someone else confirm ?
> ![photo_2020-04-26_19-56-15](https://user-images.githubusercontent.com/25624482/80312754-1314f080-87f8-11ea-8def-af7b4bff57ab.jpg)
> 
> ![photo_2020-04-26_19-56-11](https://user-images.githubusercontent.com/25624482/80312753-11e3c380-87f8-11ea-9421-b0d359c03880.jpg)

Not changed dpi and never flashed anything.Not even magisk.Pure stock floyd.I don't have any scaling issues in other edge panel things.About photo editor if do update it will fc in a few minutes

**Comment by ananjaser1211** [comment]
Alright, ill see what i can do

**Comment by Switchof** [comment]
> Alright, ill see what i can do

Thank you

**Comment by sbappii** [comment]
I had these scaling issues on several things things like like fc and edge panel. Then I flashed again and chose navbar and all scaling issues were solved

**Comment by Switchof** [comment]
> I had these scaling issues on several things things like like fc and edge panel. Then I flashed again and chose navbar and all scaling issues were solved

I don't get it..U mean with navbar or no navbar solve the issue?

**Comment by Switchof** [comment]
> Alright, ill see what i can 




> Alright, ill see what i can do

When change default dpi of 411 to 410 smart select fully visible but overall system is look smaller than before

**Comment by Switchof** [comment]
This scaling issue is caused by navbar!The only option if/to use navbar and avoid scaling issue is choose gesture type and also need to hide hint.Otherwise need to go without navbar
