### ISSUE TITLE
Can`t install .apk from Dropbox or Onedrive

### ISSUE THREAD

**Issue by Vivigens** [ananjaser1211/FloydQ_8890#57]
**Describe the bug**
Hi Guys, 
ananjaser1211, corsicanu, kill-switch, thx for an other new Custom-Rom.

After a Full-Wipe-Install of the Rom everything is fine so far. But I can`t install .apk from Dropbox & Onedrive. Permission and Rights are ok. If I klick on the .apk it says, there`s no Program to start this Filetype.

Firs of all I want to know, if I have a mistake in there!?

**Expected behavior**
Coming from Black Diamond (both Versions) I expected to install some of my .apk from the Cloud! 

**Screenshots**
Not available

**Smartphone:**
 - Device: Galaxy S7edge Exynos
 - Model: [SM G935F]

**Additional context**
Sorry, no logFile, I went back to Black Diamond Backup! I will continue with the Installation the next days... 

thx in advanced

**Comment by ananjaser1211** [comment]
Ill test it when i have the time and let you know

**Comment by Vivigens** [comment]
Strangely, it works when I use to install .apk over "My Files" - there`s a Cloud Section for OneDrive. Maybe this helps to figure out what could be the problem.

**Comment by ananjaser1211** [comment]
Neither me or the testers are able to reproduce this issue, apk installation works from both dropbox and oneDrive. 

Make sure you allowed installation of unknown APKs in the system and the app permission.
