### ISSUE TITLE
[BUG] gamee tool not working

### ISSUE THREAD

**Issue by ninja270** [ananjaser1211/FloydQ_8890#63]
**Describe the bug**
Describe your issue here. 

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930F]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by matinzd** [comment]
You may updated them via Galaxy store. Do not update it. It works perfect without updates

**Comment by ananjaser1211** [comment]
Read the F.A.Q, Dont update gametools and optimizer through galaxy apps
