### ISSUE TITLE
[BUG]camera: Front cam

### ISSUE THREAD

**Issue by DaHouK** [ananjaser1211/FloydQ_8890#64]
Front camera doesn't work in any app or in the main camera 
**Screenshots**
![Screenshot_20200429-012407_One UI Home](https://user-images.githubusercontent.com/64503869/80543698-279fe700-89b8-11ea-867e-60ff08afcda5.jpg)

 - Device: [ Galaxy S7]
 - Model: [ G930F]

**Additional context**
[2020-04-29_01.06.zip](https://github.com/ananjaser1211/FloydQ_8890/files/4548861/2020-04-29_01.06.zip)

**Comment by ananjaser1211** [comment]
No such issue here, the front camera works just fine.

try clearing camera data or figure out what happened so it broke, the logs provided contain zero information, use the loggingkit method next time
