### ISSUE TITLE
[BUG] Notification Panel Quick Pull-down 

### ISSUE THREAD

**Issue by DirNotAvailable** [ananjaser1211/FloydQ_8890#66]
Notification panel Quick Pull down i.e. scrolling down from anywhere on home screen to open NP does not work.
**Priority level**, may be little to none, but still wanted to let you know as this feature is crucial to me😢. 

**To Reproduce**
1. Hold on Home screen to till it zooms out and you see widget, wallpaper, themes and home 
    screen setting toggles on bottom of screen.
2. Click on 'Home screen setting'
3. Scroll down to 'Swipe down for notification panel'
4. It enables but on home screen, scrolling down does nothing.

**Expected behavior**
Scrolling down from anywhere on home screen should open NP.

**Smartphone:**
 - Device: [e.g. Galaxy S7E]
 - Model: [e.g. G935FD]

One more thing that Infinity wallpaper bug, I read it is fixed in Internal V2. If it is feasible, can you provide the fix may be a 'flashable zip' or something like that. If not no worries. Other than that 11/10, haven't seen a OneUI rom since ages that does not heat up my phone till now. Amazing Work👍.

**Comment by ananjaser1211** [comment]
Well. the feature is working as expected here.. did you do any mods ? changed launchers ? etc

**Comment by DirNotAvailable** [comment]
No, I didn't use any mods nor I changed any launcher, nothing of that sort.

**Comment by DirNotAvailable** [comment]
Ok as you said it is working, then it is I am going to reflash the rom with f2fs (I forgot to that before). What about the Infinity wallpaper fix?

**Comment by ananjaser1211** [comment]
> Ok as you said it is working, then it is I am going to reflash the rom with f2fs (I forgot to that before). What about the Infinity wallpaper fix?
i dont think using f2fs will change anything regarding this bug honestly

wallpaper fix is an entire rebase . cant be put in a flash-bale

ill close this issue since no one else seems to be having it in our group aswell

**Comment by shariq342** [comment]
Working fine here. I guess he didn't see the option in Home Settings 
![Screenshot_20200507-151614_One UI Home](https://user-images.githubusercontent.com/61206202/81283233-bc1fde80-9075-11ea-82b3-80b7b209003f.jpg)

**Comment by dll94** [comment]
Hey guys im the OP of #77 I ended up reflashing this rom after trying every rom on xda for my phone, and the bug is gone. It works now
