### ISSUE TITLE
[Features Request] Rounded Corner, App drawer Icon list, Quick Panel Layout etc.

### ISSUE THREAD

**Issue by DirNotAvailable** [ananjaser1211/FloydQ_8890#67]
Nothing more damming than to ask for beauty features while the rom is in its early stages. So just a humble request, nothing demanding.

**Rounded Corner**
I have read some one asked rounded UI throughout the entire UI. What I like to be on the contrary, is Corner UI for Notification Panel option in Aroma.

**App drawer Icon list**
Increase number of columns and rows on app drawer screen. May be 2 or 3 more layouts.

**Quick Panel Layout**
On Oreo and OneUI 1.0, there is this option where you can increase the number of toggles on single screen of quick panel. I think it has something to do with Samsung, I'm not sure, but I just wanted to let you know, may be it can be changed.

**Theme Center Mod**
I have scorched google for this thing but I have found nothing useful but redacted xda forums till a couple of months ago I found an Oreo ROM with the fix. May be the mod can be added in this ROM. what I am asking here is can I use that modded themecenter.apk in this ROM. Or may be you can add that mod in aroma in upcoming release/s.

Now I know, it is not a good time. I just wanted to let you know may be you consider them in future.
**Smartphone:**
 - Device: [e.g. Galaxy S7]
 - Model: [e.g. G930FD]

**Comment by ananjaser1211** [comment]
Rounded corner as per #56 is what will be added, the stock behavior as an aroma feature.

so whatever is rounded in the S9 Will be rounded here, i wont be doing any UI modding to add "Extra" stuff. as i want to keep the rom base as stock as possible

App Drawer lists and quick panel layouts also involve "Modding" beyond what is available by stock, which again, i do not want to do. a user can feel free to find ways on xda to do that themselves. on my end this ROM Will be frequently rebased, and doing such mods every release is not an easy task 

Finally, By theme center mod i assume you are talking about Trial removal, That is pretty much piracy and not allowed on XDA. will not happen
