### ISSUE TITLE
[BUG] TouchWiz Home broken gestures

### ISSUE THREAD

**Issue by dll94** [ananjaser1211/FloydQ_8890#77]
Home screen swipe down for quick settings doesnt work on my galaxy s7 edge. option is enable
https://streamable.com/nahacr 

 S7 EDGE G930F

**Comment by ananjaser1211** [comment]
Can someone confirm / deny this bug please
as mentioned in #66 it worked without issue here so i can't see what is wrong

**Comment by AndyTommo** [comment]
Works fine for me on my flat S7

**Comment by shariq342** [comment]
@ananjaser1211 Working fine. He must have not seen the option in Home Settings

**Comment by ananjaser1211** [comment]
In this video he does have it enabled. yet its not working.

Not sure why really, it still works on my end aswell since the last report

**Comment by shariq342** [comment]
Uninstall Updates of OneUI Home. CLEAR DATA AND CACHE. Then check

**Comment by dll94** [comment]
Hey guys im the OP of #77 I ended up reflashing this rom after trying every rom on xda for my phone, and the bug is gone. It works now
