### ISSUE TITLE
[BUG] First start - touch screen not fully working

### ISSUE THREAD

**Issue by floviolleau** [ananjaser1211/FloydQ_8890#79]
**Describe the bug**

Hello !

Thanks for your amazing job!

I tried to install and run it on a S7 edge G935F exynos and I have a weird issue:

After flashing only the rom and rebooting, when I arrive at the first screen with choosing the language, I cannot click on the bue button to start the welcome flow. The touch screen seems to not be active.

If I change the volume, sliders pops on top of the screen and I can move the sliders by touching the screen. Home button does nothing. If I short press the power button, it turns off the screen and same for turning it on. A long press on the power button, show shutdown/reboot menu but I cannot click on reboot. Only Shutdown work.

If I reboot and put a sim card inside it, the first screen that is shown is PIN code screen and if I touch to put enter my pin, nothing happens.

Any ideas?
Thanks 

**To Reproduce**
1. Fresh install (only the rom)
2. First start
3. Cannot enter PIN code, screen do not respond

**Expected behavior**
Screen fully responsive to touch

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: S7 edge
 - Model: G935F international bought from France

**Additional context**

**Comment by ananjaser1211** [comment]
If you have a samsung case on the phone (clear view, sview whatever)
Remove it. and that will fix the problem

**Comment by floviolleau** [comment]
Hi,

Thanks for the quick answer!

Amazing! Do you you know why we have this behavior?

Another question how future releases will be delivered? Will we need to wipe all on a future install?

Thanks and take care.

**Comment by ananjaser1211** [comment]
@floviolleau Due to broken NFC. Smart Cases show broken behaviors. Flipped states and so on 

Updates will be dirty flashed on top of your existing rom data. No wipe will be needed

**Comment by floviolleau** [comment]
Thanks.

I hope NFC will be available in a future update soon!

Thanks for your amazing job!

I chose your room because I needed wifi calls (I live in the country side where coverage is very very very poor) and this is the only room where it works fine!
