### ISSUE TITLE
[BUG] Samsung live wallpapers don't work

### ISSUE THREAD

**Issue by oopsitsdeleted** [ananjaser1211/FloydQ_8890#81]
**Describe the bug**
When I try to set the Samsung live wallpapers, my phone stops and says systumui crashed, my phone doesn't turn off or anything, it just stops for a while and has the bubble pop up.

**To Reproduce**
1. Go to settings
2. Click on wallpapers
3. Click on my wallpapers 
4. Click on infinity wallpapers
5. Try to apply it
6. See error

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S7 Edge]
 - Model: [e.g. G935FD]

**Additional context**
- Gather logs by using [LoggingKit](https://bit.ly/3anwSuW) when applicable

**Comment by ananjaser1211** [comment]
Duplicate #1
